//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPlans_by_WFP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int task_id { get; set; }
        public Nullable<int> task_author_id { get; set; }
        public Nullable<int> task_category_id { get; set; }
        public string task_title { get; set; }
        public string task_description { get; set; }
        public string task_status { get; set; }
        public string task_priority { get; set; }
        public Nullable<System.DateTime> task_created_at { get; set; }
        public Nullable<System.DateTime> task_updated_at { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
